"""initial phase zero schema

Revision ID: 842ecccf59e1
Revises:
Create Date: 2026-07-18 18:48:50.677584
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "842ecccf59e1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invite_code_used", sa.String(length=100), nullable=True),
        sa.Column("school_calendar_id", sa.String(length=300), nullable=True),
        sa.Column("drive_root_folder_id", sa.String(length=300), nullable=True),
        sa.Column("drive_root_folder_name", sa.String(length=200), nullable=False),
        sa.Column("notion_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "calendar_links",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("moodle_event_id", sa.String(length=200), nullable=False),
        sa.Column("gcal_event_id", sa.String(length=300), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("event_kind", sa.String(length=50), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "moodle_event_id"),
    )
    op.create_index(op.f("ix_calendar_links_user_id"), "calendar_links", ["user_id"], unique=False)
    op.create_table(
        "control_commands",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("command", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_commands_command"), "control_commands", ["command"], unique=False
    )
    op.create_index(
        op.f("ix_control_commands_user_id"), "control_commands", ["user_id"], unique=False
    )
    op.create_table(
        "courses",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("moodle_course_id", sa.BigInteger(), nullable=False),
        sa.Column("course_code", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_tracked", sa.Boolean(), nullable=False),
        sa.Column("drive_folder_id", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "moodle_course_id"),
    )
    op.create_index(op.f("ix_courses_user_id"), "courses", ["user_id"], unique=False)
    op.create_table(
        "invite_codes",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("claimed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["claimed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_invite_codes_claimed_by_user_id"),
        "invite_codes",
        ["claimed_by_user_id"],
        unique=False,
    )
    op.create_table(
        "job_runs",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("items_processed", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_runs_job_name"), "job_runs", ["job_name"], unique=False)
    op.create_index(op.f("ix_job_runs_user_id"), "job_runs", ["user_id"], unique=False)
    op.create_table(
        "moodle_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("ws_token_enc", sa.Text(), nullable=False),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_ok_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_moodle_accounts_user_id"), "moodle_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "notification_log",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("telegram_message_id", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_log_event_type"), "notification_log", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_notification_log_user_id"), "notification_log", ["user_id"], unique=False
    )
    op.create_table(
        "notification_prefs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_toggles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column("digest_enabled", sa.Boolean(), nullable=False),
        sa.Column("digest_time", sa.Time(), nullable=True),
        sa.Column("paused_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_notification_prefs_user_id"), "notification_prefs", ["user_id"], unique=False
    )
    op.create_table(
        "oauth_credentials",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("refresh_token_enc", sa.Text(), nullable=False),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider"),
    )
    op.create_index(
        op.f("ix_oauth_credentials_user_id"), "oauth_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "seen_messages",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("moodle_message_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "classification",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "moodle_message_id"),
    )
    op.create_index(op.f("ix_seen_messages_user_id"), "seen_messages", ["user_id"], unique=False)
    op.create_table(
        "telegram_links",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.String(length=100), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_telegram_links_user_id"), "telegram_links", ["user_id"], unique=False)
    op.create_table(
        "course_prefs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_enabled", sa.Boolean(), nullable=False),
        sa.Column("files_enabled", sa.Boolean(), nullable=False),
        sa.Column("messages_enabled", sa.Boolean(), nullable=False),
        sa.Column("drive_folder_override", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id"),
    )
    op.create_index(op.f("ix_course_prefs_course_id"), "course_prefs", ["course_id"], unique=False)
    op.create_index(op.f("ix_course_prefs_user_id"), "course_prefs", ["user_id"], unique=False)
    op.create_table(
        "file_ledger",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("moodle_file_url", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("timemodified", sa.BigInteger(), nullable=True),
        sa.Column("filesize", sa.BigInteger(), nullable=True),
        sa.Column("drive_file_id", sa.String(length=300), nullable=False),
        sa.Column("drive_path", sa.Text(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "moodle_file_url"),
    )
    op.create_index(op.f("ix_file_ledger_course_id"), "file_ledger", ["course_id"], unique=False)
    op.create_index(op.f("ix_file_ledger_user_id"), "file_ledger", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_ledger_user_id"), table_name="file_ledger")
    op.drop_index(op.f("ix_file_ledger_course_id"), table_name="file_ledger")
    op.drop_table("file_ledger")
    op.drop_index(op.f("ix_course_prefs_user_id"), table_name="course_prefs")
    op.drop_index(op.f("ix_course_prefs_course_id"), table_name="course_prefs")
    op.drop_table("course_prefs")
    op.drop_index(op.f("ix_telegram_links_user_id"), table_name="telegram_links")
    op.drop_table("telegram_links")
    op.drop_index(op.f("ix_seen_messages_user_id"), table_name="seen_messages")
    op.drop_table("seen_messages")
    op.drop_index(op.f("ix_oauth_credentials_user_id"), table_name="oauth_credentials")
    op.drop_table("oauth_credentials")
    op.drop_index(op.f("ix_notification_prefs_user_id"), table_name="notification_prefs")
    op.drop_table("notification_prefs")
    op.drop_index(op.f("ix_notification_log_user_id"), table_name="notification_log")
    op.drop_index(op.f("ix_notification_log_event_type"), table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index(op.f("ix_moodle_accounts_user_id"), table_name="moodle_accounts")
    op.drop_table("moodle_accounts")
    op.drop_index(op.f("ix_job_runs_user_id"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_job_name"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index(op.f("ix_invite_codes_claimed_by_user_id"), table_name="invite_codes")
    op.drop_table("invite_codes")
    op.drop_index(op.f("ix_courses_user_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_control_commands_user_id"), table_name="control_commands")
    op.drop_index(op.f("ix_control_commands_command"), table_name="control_commands")
    op.drop_table("control_commands")
    op.drop_index(op.f("ix_calendar_links_user_id"), table_name="calendar_links")
    op.drop_table("calendar_links")
    op.drop_table("users")
    # ### end Alembic commands ###
