"""enforce tenant ownership and service heartbeat

Revision ID: 8edc3a595146
Revises: 842ecccf59e1
Create Date: 2026-07-18 19:05:30.970385
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8edc3a595146"
down_revision: str | None = "842ecccf59e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_heartbeats",
        sa.Column("worker_name", sa.String(length=100), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_worker_heartbeats_worker_name"), "worker_heartbeats", ["worker_name"], unique=False
    )
    op.drop_constraint(op.f("course_prefs_course_id_fkey"), "course_prefs", type_="foreignkey")
    op.drop_constraint(op.f("course_prefs_user_id_fkey"), "course_prefs", type_="foreignkey")
    op.create_unique_constraint("uq_courses_user_id_id", "courses", ["user_id", "id"])
    op.create_foreign_key(
        "fk_course_prefs_course_owner",
        "course_prefs",
        "courses",
        ["user_id", "course_id"],
        ["user_id", "id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("file_ledger_course_id_fkey"), "file_ledger", type_="foreignkey")
    op.drop_constraint(op.f("file_ledger_user_id_fkey"), "file_ledger", type_="foreignkey")
    op.create_foreign_key(
        "fk_file_ledger_course_owner",
        "file_ledger",
        "courses",
        ["user_id", "course_id"],
        ["user_id", "id"],
        ondelete="CASCADE",
    )
    op.execute(
        """
        INSERT INTO worker_heartbeats (id, worker_name, observed_at)
        SELECT id, 'scheduler', COALESCE(finished_at, started_at)
        FROM job_runs
        WHERE user_id IS NULL AND job_name = 'heartbeat'
        """
    )
    op.execute("DELETE FROM job_runs WHERE user_id IS NULL")
    op.alter_column("job_runs", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job_runs", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint("fk_file_ledger_course_owner", "file_ledger", type_="foreignkey")
    op.create_foreign_key(
        op.f("file_ledger_user_id_fkey"),
        "file_ledger",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("file_ledger_course_id_fkey"),
        "file_ledger",
        "courses",
        ["course_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_course_prefs_course_owner", "course_prefs", type_="foreignkey")
    op.create_foreign_key(
        op.f("course_prefs_user_id_fkey"),
        "course_prefs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("course_prefs_course_id_fkey"),
        "course_prefs",
        "courses",
        ["course_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_courses_user_id_id", "courses", type_="unique")
    op.drop_index(op.f("ix_worker_heartbeats_worker_name"), table_name="worker_heartbeats")
    op.drop_table("worker_heartbeats")
    # ### end Alembic commands ###
